<script type="text/javascript" src="{{ asset('dist-front/js/jquery.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('dist-front/js/jquery.migrate.js') }}"></script>
<script type="text/javascript" src="{{ asset('dist-front/js/jquery.bxslider.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('dist-front/js/jquery.magnific-popup.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('dist-front/js/bootstrap.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('dist-front/js/jquery.ticker.js') }}"></script>
<script type="text/javascript" src="{{ asset('dist-front/js/jquery.imagesloaded.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('dist-front/js/jquery.isotope.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('dist-front/js/owl.carousel.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('dist-front/js/retina-1.1.0.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('dist-front/js/script.js ')}}"></script>